### ISSUE TITLE
Duo Authentication Issue

### ISSUE THREAD

**Issue by lukaalex** [venth/aws-adfs#105]
It appears that Duo is no longer sending a response with the key 'cookie' . I'm just wondering if others have run into this issue on ADFS4.0 and Duo.

```Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/login.py", line 144, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config, username, password, sspi=sspi)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/authenticator.py", line 31, in authenticate
    principal_roles, assertion, aws_session_duration = extract_strategy()
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/authenticator.py", line 111, in extract
    return duo_auth.extract(html_response, config.ssl_verification, session)
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/_duo_authenticator.py", line 67, in extract
    ssl_verification_enabled
  File "/usr/local/lib/python3.7/site-packages/aws_adfs/_duo_authenticator.py", line 177, in _authentication_result
    auth_signature = response.json()['response']['cookie']
KeyError: 'cookie'
```

**Comment by ronaldmexico** [comment]
Seeing the same issue.

**Comment by lukaalex** [comment]
Does anyone happen to have a working version with ADFS4.0 and Duo?  I would like to see the format of the data in `auth_signature = response.json()['response']['cookie']`

**Comment by josh-at-imperva** [comment]
same issue as well... not sure if Duo changed something or there's a communication issue or what... but I can log into Duo + ADFS other ways just fine

**Comment by venth** [comment]
Currently I don’t have access to an instance of adfs which is integrated with Duo, unfortunately. I’ve thought that instead of page scrapping I could use adfs api to gain authentication token. The python library is described here: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-authentication-libraries

Then probably all second factor authentication providers can be treated in similar way. I’m not sure. I came across this library recently and still have to figure out its usage.

**Comment by bghinkle** [comment]
The above pull request fixes the issue - basically we need to follow a result URL that's provided from the initial authentication, and that result URL provides the cookie for the authentication result.
