### ISSUE TITLE
requests.exceptions.SSLError: [Errno 2] - aws-adfs version 0.1.1

### ISSUE THREAD

**Issue by nalindak** [venth/aws-adfs#11]
Hi there,

We are getting `SSL` exceptions with the latest version 0.1.1 which running in Mac (However it's continue to work in version 0.0.9). 

- OS is Mac OS X EI Capitan Version `10.11.6`
- Python `2.7`

We get following error when we try to `aws-adfs login --adfs-host=your-adfs-hostname`

Error is the error,
```
Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/aws_adfs/login.py", line 60, in login
    principal_roles, assertion = authenticator.authenticate(config)
  File "/Library/Python/2.7/site-packages/aws_adfs/authenticator.py", line 12, in authenticate
    password=password,
  File "/Library/Python/2.7/site-packages/aws_adfs/html_roles_fetcher.py", line 54, in fetch_html_encoded_roles
    'AuthMethod': 'urn:amazon:webservices'
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 522, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 475, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 596, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 497, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [Errno 2] No such file or directory
```

**Comment by venth** [comment]
Thanks for the notification. I'll look into it.

**Comment by venth** [comment]
Hi @nalindak,

I've tried to reproduce the issue by removal of ca certs from my os. I've succeeded to produce the same stacktrace.

In case of osx, I think that providing ssl certs could be done like that:
```
brew install openssl
export REQUESTS_CA_BUNDLE=/usr/local/etc/openssl/certs/cacert.pem
```
It would be good to place REQUESTS_CA_BUNDLE into you .bashrc, I believe.

Please let me know, if providing REQUESTS_CA_BUNDLE with location of cacert helped.

**Comment by venth** [comment]
I've prepared the fix. The version 0.1.2 contains the fix.

**Comment by nalindak** [comment]
Hi @venth Installed and checked version `0.1.2` which fixed the issue. Thank you so much for your prompt response and the fix.

**Comment by venth** [comment]
My pleasure, may I close the isssue? 😀

**Comment by nalindak** [comment]
@venth Yep let's close this. Cheers
