### ISSUE TITLE
Failed with DUO MFA enabled. 

### ISSUE THREAD

**Issue by eric-nord** [venth/aws-adfs#24]
AWS CLI access is successful with ADFS but fails after DUO MFA is enabled in ADFS.

**Comment by eric-nord** [comment]
Think it's in html_roles_fetcher.py around line 45. 
When It's trying to fetch roles from the AWS "Select a Role" page it fails as the DUO MFA page loads instead and waits for the user to accept the push. 

May need to target  the button text "Send Me a Push" and click it until the user accepts the MFA Push.

**Comment by venth** [comment]
Unfortunately I don't have access to adfs installation that uses MFA to authenticate an user. If you have link to any vagrant / docker machine description that I could spin up then I could tell more about this issue.

**Comment by eric-nord** [comment]
I have credentials for a sample login if you'd like please email me
directly @ eric.w.nord@gmail.com

**Comment by eric-nord** [comment]
Here's the error - makes me think it retires parsing the AWS HTML a few times then fails not giving the MFA challange time to fire (and the user time to respond):
ERICN:/mnt/c/Users/XXX$ aws-adfs -v login --adfs-host https://XXXXXXXX.XXX.XXX/adfs/ls/IdpInitiatedSignOn.aspx
`2017-03-14 10:07:37,910 [connectionpool connectionpool.py:_new_conn] [41-MainProcess] [140390998083392-MainThread] - DEBUG: Starting new HTTPS connection (1): https
Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/login.py", line 82, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config)
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/authenticator.py", line 13, in authenticate
    password=password,
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/html_roles_fetcher.py", line 55, in fetch_html_encoded_roles
    'AuthMethod': provider_id
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 535, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 487, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='https', port=443): Max retries exceeded with url: //XXXX.XXX.XXX/adfs/ls/IdpInitiatedSignOn.aspx/adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7faf52398750>: Failed to establish a new connection: [Errno -2] Name or service not known',))`

**Comment by venth** [comment]
Duo security integration is available in version 0.3.0. Thanks @eric-nord for bringing the issue, commitment and help 👍

**Comment by venth** [comment]
Duo Security integration is delivered with version 0.3.0. @eric-nord may I ask you to close the issue?

**Comment by eric-nord** [comment]
Thank you @venth,

You're awesome to work with.

**Comment by eric-nord** [comment]
Yes of course
