### ISSUE TITLE
fido2 1.0.0 breaks aws-adfs

### ISSUE THREAD

**Issue by erpel** [venth/aws-adfs#243]
Installing on macOS in a fresh virtualenv pulls in the newly released fido2 as a dependency. This breaks aws-adfs.
Manually downgrading to 0.9.3 restores functionality.
aws-adfs will either need to adapt to 1.0.0 or depend on <1.0.0 for now.
```
python3 -m pip install aws-adfs
Collecting aws-adfs
  Using cached aws_adfs-2.2.1-py3-none-any.whl (37 kB)
Collecting requests-kerberos
  Using cached requests_kerberos-0.14.0-py2.py3-none-any.whl (11 kB)
Collecting requests
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting boto3<2.0.0,>=1.20.50
  Using cached boto3-1.24.4-py3-none-any.whl (132 kB)
Collecting lxml
  Using cached lxml-4.9.0-cp310-cp310-macosx_12_0_arm64.whl
Collecting configparser
  Using cached configparser-5.2.0-py3-none-any.whl (19 kB)
Collecting click
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting botocore>=1.12.6
  Using cached botocore-1.27.4-py3-none-any.whl (8.9 MB)
Collecting fido2>=0.9.3
  Using cached fido2-1.0.0-py3-none-any.whl (198 kB)
Collecting jmespath<2.0.0,>=0.7.1
  Using cached jmespath-1.0.0-py3-none-any.whl (23 kB)
Collecting s3transfer<0.7.0,>=0.6.0
  Using cached s3transfer-0.6.0-py3-none-any.whl (79 kB)
Collecting urllib3<1.27,>=1.25.4
  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)
Collecting python-dateutil<3.0.0,>=2.1
  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)
Collecting cryptography!=35,<40,>=2.6
  Using cached cryptography-37.0.2-cp36-abi3-macosx_10_10_universal2.whl (5.3 MB)
Collecting idna<4,>=2.5
  Using cached idna-3.3-py3-none-any.whl (61 kB)
Collecting certifi>=2017.4.17
  Using cached certifi-2022.5.18.1-py3-none-any.whl (155 kB)
Collecting charset-normalizer~=2.0.0
  Using cached charset_normalizer-2.0.12-py3-none-any.whl (39 kB)
Collecting pyspnego[kerberos]
  Using cached pyspnego-0.5.2-py2.py3-none-any.whl (123 kB)
Collecting cffi>=1.12
  Using cached cffi-1.15.0-cp310-cp310-macosx_11_0_arm64.whl (173 kB)
Collecting six>=1.5
  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting krb5>=0.3.0
  Using cached krb5-0.3.0-cp310-cp310-macosx_11_0_arm64.whl (715 kB)
Collecting gssapi>=1.5.0
  Using cached gssapi-1.7.3-cp310-cp310-macosx_11_0_arm64.whl (560 kB)
Collecting pycparser
  Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
Collecting decorator
  Using cached decorator-5.1.1-py3-none-any.whl (9.1 kB)
Installing collected packages: urllib3, six, pycparser, lxml, krb5, jmespath, idna, decorator, configparser, click, charset-normalizer, certifi, requests, python-dateutil, gssapi, cffi, cryptography, botocore, s3transfer, pyspnego, fido2, boto3, requests-kerberos, aws-adfs
Successfully installed aws-adfs-2.2.1 boto3-1.24.4 botocore-1.27.4 certifi-2022.5.18.1 cffi-1.15.0 charset-normalizer-2.0.12 click-8.1.3 configparser-5.2.0 cryptography-37.0.2 decorator-5.1.1 fido2-1.0.0 gssapi-1.7.3 idna-3.3 jmespath-1.0.0 krb5-0.3.0 lxml-4.9.0 pycparser-2.21 pyspnego-0.5.2 python-dateutil-2.8.2 requests-2.27.1 requests-kerberos-0.14.0 s3transfer-0.6.0 six-1.16.0 urllib3-1.26.9
WARNING: You are using pip version 22.0.4; however, version 22.1.2 is available.
You should consider upgrading via the '/Users/philipp.erbelding/.virtualenvs/aws3/bin/python3 -m pip install --upgrade pip' command.
(aws3) ✔ ~aws-adfs --version
Traceback (most recent call last):
  File "/Users/philipp.erbelding/.virtualenvs/aws3/bin/aws-adfs", line 5, in <module>
    from aws_adfs.commands import cli
  File "/Users/philipp.erbelding/.virtualenvs/aws3/lib/python3.10/site-packages/aws_adfs/commands.py", line 9, in <module>
    from . import login
  File "/Users/philipp.erbelding/.virtualenvs/aws3/lib/python3.10/site-packages/aws_adfs/login.py", line 21, in <module>
    from . import authenticator, helpers, prepare, role_chooser
  File "/Users/philipp.erbelding/.virtualenvs/aws3/lib/python3.10/site-packages/aws_adfs/authenticator.py", line 5, in <module>
    from . import _duo_authenticator as duo_auth
  File "/Users/philipp.erbelding/.virtualenvs/aws3/lib/python3.10/site-packages/aws_adfs/_duo_authenticator.py", line 6, in <module>
    from fido2.client import ClientData, ClientError, Fido2Client
ImportError: cannot import name 'ClientData' from 'fido2.client' (/Users/philipp.erbelding/.virtualenvs/aws3/lib/python3.10/site-packages/fido2/client.py)
(aws3) ✘-1 ~python3 -m pip freeze
aws-adfs==2.2.1
boto3==1.24.4
botocore==1.27.4
certifi==2022.5.18.1
cffi==1.15.0
charset-normalizer==2.0.12
click==8.1.3
configparser==5.2.0
cryptography==37.0.2
decorator==5.1.1
fido2==1.0.0
gssapi==1.7.3
idna==3.3
jmespath==1.0.0
krb5==0.3.0
lxml==4.9.0
pycparser==2.21
pyspnego==0.5.2
python-dateutil==2.8.2
requests==2.27.1
requests-kerberos==0.14.0
s3transfer==0.6.0
six==1.16.0
urllib3==1.26.9
(aws3) ✔ ~python3 --version
Python 3.10.4
(aws3) ✔ ~

```

**Comment by Marc-Pons** [comment]
Same problem here

**Comment by pdecat** [comment]
I had no issue with fido2 1.0.0 on linux, so I went ahead a submitted https://github.com/venth/aws-adfs/issues/245 but I guess I'll reconsider for now.

**Comment by pdecat** [comment]
Ok, found the fix: https://github.com/venth/aws-adfs/pull/245/commits/688c1169cdd91275fbe94a86661f8a43541201d4

**Comment by erpel** [comment]
Well that looks like an even better fix, did not expect it to go so quickly. Thanks for the effort! #244 is redundant then...

**Comment by pdecat** [comment]
I've merged your PR to take a bit more time to test my other PR.

Fix released in https://github.com/venth/aws-adfs/releases/tag/2.2.2
