### ISSUE TITLE
On login, skipping profile option causes error.

### ISSUE THREAD

**Issue by cezarygerard** [venth/aws-adfs#28]
invoking following command results in error.

aws-adfs login --adfs-host=valid.host --no-ssl-verification
Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 11, in <module>
    load_entry_point('aws-adfs==0.3.2', 'console_scripts', 'aws-adfs')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/login.py", line 70, in login
    s3_signature_version,
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/prepare.py", line 38, in get_prepared_config
    _load_adfs_config_from_stored_profile(adfs_config, profile)
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/prepare.py", line 142, in _load_adfs_config_from_stored_profile
    load_from_config(adfs_config.aws_config_location, 'profile ' + profile, load_config)
TypeError: cannot concatenate 'str' and 'NoneType' objects

this works fine:
aws-adfs login --adfs-host=valid.host  --no-ssl-verification --profile=default

**Comment by venth** [comment]
Fix delivered in version 0.3.3
