### ISSUE TITLE
aws-adfs not working on macOS Sierra - System-installed Python 2.7

### ISSUE THREAD

**Issue by dsw88** [venth/aws-adfs#31]
I'm having issues getting aws-adfs to work on the system-installed Python 2.7 on macOS Sierra. The tool can be installed using pip, but when running the command "aws-adfs login --adfs-host MYHOST --profile MYPROFILE", I get the following error:

```
Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 11, in <module>
    load_entry_point('aws-adfs==0.3.3', 'console_scripts', 'aws-adfs')()
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/aws_adfs/login.py", line 76, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config)
  File "/Library/Python/2.7/site-packages/aws_adfs/authenticator.py", line 16, in authenticate
    password=password,
  File "/Library/Python/2.7/site-packages/aws_adfs/html_roles_fetcher.py", line 61, in fetch_html_encoded_roles
    'AuthMethod': provider_id
  File "/Users/trevash/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 511, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Users/trevash/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/Users/trevash/Library/Python/2.7/lib/python/site-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/Users/trevash/Library/Python/2.7/lib/python/site-packages/requests/adapters.py", line 447, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: ("bad handshake: SysCallError(54, 'Connection reset by peer')",)​
```

Any idea why this would be happening?

**Comment by venth** [comment]
Would you like to add results of the following command: `openssl s_client -connect "<your-host>:<your-port>" -showcerts -servername "<your-host>"`?

**Comment by dsw88** [comment]
Yeah sure I can do that. Is <your-host> supposed to replaced with the hostname of my ADFS server that I'm trying to talk to? Also, what would the port be? I'm not sure what port ADFS wants to talk on. Thanks!

**Comment by venth** [comment]
Ahh, my bad :) host name is your ADFS server fqdn (e.g.: adfs.example.com) and port is 443

**Comment by dsw88** [comment]
Ah ok thanks! I ran that and got the following output:
```
CONNECTED(00000003)
write:errno=54
```

**Comment by venth** [comment]
What is your version of OpenSSL?

**Comment by dsw88** [comment]
I ran "openssl version" and got this output:
```
OpenSSL 0.9.8zh 14 Jan 2016
```

**Comment by venth** [comment]
I think the server uses TLSv1.2. OpenSSL 0.9.8zh 14 Jan 2016 (bundled in osx) doesn't support it. Please upgrade openssl at least to version 1.0.1 or newer, if possible.

You may upgrade openssl via brew for instance.

**Comment by wiederhold** [comment]
same issue OSX 10.12.4:

`brew upgrade openssl'

installs OpenSSL 1.0.2k but has issues as per [@katopz](https://medium.com/@katopz/how-to-upgrade-openssl-8d005554401). Added:

`export PATH=$(brew --prefix openssl)/bin:$PATH`

to .bash_profile AND I'm able to
`openssl s_client -connect "myhost:443" -showcerts -servername "myhost"`

with the following response:

**Comment by venth** [comment]
Thanks for providing OpenSSL feedback. I'll look into the response. Right now the error looks differently. Would you like to repeat aws-adfs command with verbose parameter? Additionally please provide result of `pip freeze` command.

**Comment by wiederhold** [comment]
So w/ a nights sleep the issue appears to have resolved... My suspicion is that because I already had an open DUO authentication, but my aws-adfs login had failed, that a session somewhere needed to be cleared out...

Whatever might have been the case, the issue on Sierra is clearly the OpenSSL library, not aws-adfs. Excellent work btw

**Comment by venth** [comment]
Thank you :) Since the issue seems to be cleared out, may I ask you to close it?
