### ISSUE TITLE
Issues with Centos 7

### ISSUE THREAD

**Issue by gkalmady** [venth/aws-adfs#39]
I am running Centos 7 in a VM on Virtualbox. I am attempting to use aws-adfs to connect to my code commit repo in AWS. My Python version 2.7.12. I installed aws-adfs using pip. The aws-adfs version is 0.3.3
On both aws-adfs --version and aws-adfs --help I get the following error.
aws-adfs --help
Traceback (most recent call last):
  File "/usr/bin/aws-adfs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 3007, in <module>
    working_set.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 728, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
    requirements.extend(dist.requires(req.extras)[::-1])
  File "/usr/lib/python2.7/site-packages/pkg_resources.py", line 2497, in requires
    "%s has no such extra feature %r" % (self, ext)
pkg_resources.UnknownExtra: requests 2.6.0 has no such extra feature 'security'

**Comment by venth** [comment]
I've tried to verify this issue by usage of docker and latest centos7 image.
I created Dockerfile as follows:
```
FROM centos:7

RUN rpm -iUvh http://dl.fedoraproject.org/pub/epel/7/x86_64/e/epel-release-7-9.noarch.rpm
RUN yum install -y python-pip
RUN yum group install -y "Development Tools"
RUN yum install -y openssl-devel.x86_64 python-devel.x86_64
RUN pip install aws-adfs
```

and docker-compose.yml:
```
version: '3'
services:
  centos7:
    build:
      context: .
```

Then I've executed following command:
`docker-compose run centos7 aws-adfs --version`

It returned current version of installed latest aws-adfs. In my case it was 0.3.3

I think that you somehow omitted during installation of security extras of requests module. To fix the issue just try to install them via:
`pip install requests[security]` 

If you installed aws-adfs with `sudo` use sudo to install `requests[security]` as well.

**Comment by gkalmady** [comment]
Thanks for the quick  response Artur. I tried the above.
I get nothing to install for the group Development tools.
openssl-devel successfully installed with version 1:1.0.1e-60.e17_3.1

python-devel successfully installed with version 2.7.5-48.e17

On pip install I get the warning
Requirement already satisfied: requests[security] in /usr/lib/python2.7/site-packages
requests 2.6.0 does not provide the extra 'security'
Could you please help me with that?

**Comment by gkalmady** [comment]
I upgraded by requests to 2.14 using pip install requests --upgrade
I tried pip install requests[security] again. 
Now I get
gkalmady@gkcentosdev bin]$ sudo pip install requests[security]
Requirement already satisfied: requests[security] in /usr/lib/python2.7/site-packages
Requirement already satisfied: idna>=2.0.0; extra == "security" in /usr/lib/python2.7/site-packages (from requests[security])
Collecting cryptography>=1.3.4; extra == "security" (from requests[security])
  Using cached cryptography-1.8.1.tar.gz
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/site-packages/pip/commands/install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "/usr/lib/python2.7/site-packages/pip/req/req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 412, in run_egg_info
    self.setup_py, self.name,
  File "/usr/lib/python2.7/site-packages/pip/req/req_install.py", line 387, in setup_py
    import setuptools  # noqa
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
    import setuptools.version
  File "/usr/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
    import pkg_resources
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() takes exactly 2 arguments (1 given)

**Comment by venth** [comment]
Please try to reinstall requests[security]: `sudo pip uninstall requests[security]` and then install `sudo pip install requests[security]`

**Comment by gkalmady** [comment]
Thanks Artur,
  I started with a Centos Everything ISO and followed your installation instructions. It came with Python 2.7.5, out of the box. I performed a pip upgrade of requests[security]. This was followed by install aws-adfs and it worked.
I would close this issue now. However I would like to upgrade to Python 2.7.12 and I have not gotten that scenario working. I am going to try out that next.
