### ISSUE TITLE
Python 3 compatible?

### ISSUE THREAD

**Issue by eikenb** [venth/aws-adfs#41]
In the readme you credit @brandond with Python 3 compatibility, and your 'known issues' section lists python 3.2 as not supported (hinting that python 3.3+ is supported). I'm getting the similar error that was reported in #32 with python3.4. He closed the issue saying he got it working with python 2.7.

Is aws-adfs python-3 compatible?

**Comment by eikenb** [comment]
The error is...

$ aws-adfs --help
Traceback (most recent call last):
  File "/home/jae/scratch/awscli/venv/bin/aws-adfs", line 9, in <module>
    load_entry_point('aws-adfs==0.3.3', 'console_scripts', 'aws-adfs')()
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 1018, in parse_args
    rest = Command.parse_args(self, ctx, args)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 1404, in handle_parse_result
    self.callback, ctx, self, value)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 78, in invoke_param_callback
    return callback(ctx, param, value)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/core.py", line 809, in show_help
    echo(ctx.get_help(), color=ctx.color)
  File "/home/jae/scratch/awscli/venv/lib/python3.4/site-packages/click/utils.py", line 259, in echo
    file.write(message)
  File "/usr/lib/python3.4/codecs.py", line 369, in write
    self.stream.write(data)
TypeError: must be str, not bytes

**Comment by eikenb** [comment]
Trying a few other things the errors are all similar and always come out of the Click package. 
It is using click-6.7.

**Comment by venth** [comment]
Please, paste here the result of the command: `pip freeze` 
I'll setup same environment and try to reproduce the issue.

**Comment by venth** [comment]
Hmm, got it. The change introduced in click version 6.7 causes the issue.

**Comment by eikenb** [comment]
Great. Thanks. I'll be sure to test it as soon as the fix lands. Sorry I don't have time to work on it myself right now.

**Comment by venth** [comment]
delivered with version 0.3.4

**Comment by eikenb** [comment]
I can no longer reproduce this bug with version 0.3.4. Thanks.
