### ISSUE TITLE
Dependency incompatibility with botocore 1.6.0+

### ISSUE THREAD

**Issue by QuantumGrizzly** [venth/aws-adfs#52]
Hello,

I had an issue after updating the awscli to the version (1.11.136).

```PowerShell
PS X:\Work\projects> aws-adfs login --adfs-host adfs.Company.com
Traceback (most recent call last):
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.6.3 (c:\users\User\appdata\local\programs\python\python36\lib\site-packages), Requirement.parse('botocore<1.6.0,>=1.5.0'), {'boto3'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python36\Scripts\aws-adfs-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\users\User\appdata\local\programs\python\python36\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore<1.6.0,>=1.5.0' distribution was not found and is required by boto3
```

I worked around the problem by downgrading botocore to version 1.5.95.

```PowerShell
PS X:\Work\projects> pip install botocore==1.5.95
Collecting botocore==1.5.95
  Downloading botocore-1.5.95-py2.py3-none-any.whl (3.6MB)
    100% |████████████████████████████████| 3.6MB 316kB/s
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in c:\users\User\appdata\local\programs\python\python36\lib\site-packages (from botocore==1.5.95)
Requirement already satisfied: docutils>=0.10 in c:\users\User\appdata\local\programs\python\python36\lib\site-packages (from botocore==1.5.95)
Requirement already satisfied: jmespath<1.0.0,>=0.7.1 in c:\users\User\appdata\local\programs\python\python36\lib\site-packages (from botocore==1.5.95)
Requirement already satisfied: six>=1.5 in c:\users\User\appdata\local\programs\python\python36\lib\site-packages (from python-dateutil<3.0.0,>=2.1->botocore==1.5.95)
Installing collected packages: botocore
  Found existing installation: botocore 1.6.0
    Uninstalling botocore-1.6.0:
      Successfully uninstalled botocore-1.6.0
Successfully installed botocore-1.5.95
```

But a better solution would to update the dependency requirements for botocore.

# Versions
awscli (1.11.136)
boto3 (1.4.4)
botocore (1.5.95)
aws-adfs (0.2.3)

**Comment by venth** [comment]
Hi, I verified versions declared in the setup file. `aws-adfs` uses latest version of following libraries:
* lxml
* click
* boto3
* requests[security]
* configparser

I think that the fix could look like that:
*  `pip uninstall botocore boto3 && pip install boto3` then a proper version for boto3 library will be installed along with boto3.

In case, the fix will not work, please provide `pip freeze` results so I will be able to re-create your python environment and reproduce the issue.

**Comment by mbudzinski** [comment]
I can confirm that the above fix works.

**Comment by venth** [comment]
Solved by keeping in synch with awscli, botocore and boto3 introduced in version 0.3.13
