### ISSUE TITLE
SSL certificate verify failed even with --no-ssl-verification

### ISSUE THREAD

**Issue by pittjl** [venth/aws-adfs#59]
Windows 10, python 2.7.14. Get normal SSL warnings, then it bombs at the bottom. 

aws-adfs login --adfs-host=login.xxxxxxxxx.com --no-ssl-verification

c:\users\jopittman\python27\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\users\jopittman\python27\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\users\jopittman\python27\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\users\jopittman\python27\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\users\jopittman\python27\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
c:\users\jopittman\python27\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
Traceback (most recent call last):
  File "C:\Users\jopittman\Python27\Scripts\aws-adfs-script.py", line 11, in <module>
    load_entry_point('aws-adfs==0.4.3', 'console_scripts', 'aws-adfs')()
  File "c:\users\jopittman\python27\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\jopittman\python27\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\jopittman\python27\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\jopittman\python27\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\jopittman\python27\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\jopittman\python27\lib\site-packages\aws_adfs\login.py", line 129, in login
    DurationSeconds=3600,
  File "c:\users\jopittman\python27\lib\site-packages\botocore\client.py", line 312, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\client.py", line 588, in _make_api_call
    operation_model, request_dict)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\endpoint.py", line 141, in make_request
    return self._send_request(request_dict, operation_model)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\endpoint.py", line 170, in _send_request
    success_response, exception):
  File "c:\users\jopittman\python27\lib\site-packages\botocore\endpoint.py", line 249, in _needs_retry
    caught_exception=caught_exception, request_dict=request_dict)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\hooks.py", line 227, in emit
    return self._emit(event_name, kwargs)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\hooks.py", line 210, in _emit
    response = handler(**kwargs)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\retryhandler.py", line 183, in __call__
    if self._checker(attempts, response, caught_exception):
  File "c:\users\jopittman\python27\lib\site-packages\botocore\retryhandler.py", line 251, in __call__
    caught_exception)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\retryhandler.py", line 277, in _should_retry
    return self._checker(attempt_number, response, caught_exception)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\retryhandler.py", line 317, in __call__
    caught_exception)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\retryhandler.py", line 223, in __call__
    attempt_number, caught_exception)
  File "c:\users\jopittman\python27\lib\site-packages\botocore\retryhandler.py", line 359, in _check_caught_exception
    raise caught_exception
botocore.vendored.requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)

**Comment by pittjl** [comment]
The answer on our end was to bypass SSL inspection on sts.amazonaws.com, and that made the code work. Not ideal, as turning off ssl verification should turn it off completely.

**Comment by venth** [comment]
Sorry for late response. Which version of aws-adfs do you use? Would you like to share results of: `pip freeze` command? I’ll try to reproduce the issue.

**Comment by pittjl** [comment]
In the end it appears the issue was on totally on our end, and does involve trusting certificates of the various STS endpoints and IP's. I don't think there's anything you can do in code, as anything that relies on boto seems to bomb like this. I'll close this out.

**Comment by venth** [comment]
Thank you for sharing the knowledge about sets endpoints and certificates 😀
