### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017a' in position 705: ordinal not in range(128)

### ISSUE THREAD

**Issue by dzinek** [venth/aws-adfs#6]
Version: aws-adfs-0.0.3
Uname: Linux mo-01-0187 4.4.0-28-generic #47-Ubuntu SMP Fri Jun 24 10:09:13 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
Charset: pl_PL.UTF-8

```
~/s/o/d/d/s/jenkins (master) $ aws-adfs login --profile=shared-resource-admin --adfs-host=adfs.int.hrs.com --no-ssl-verification

Traceback (most recent call last):
  File "/home/tnowodzinski/.local/bin/aws-adfs", line 11, in <module>
    sys.exit(cli())
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/aws_adfs/login.py", line 68, in login
    principal_roles, assertion = _authenticate(config)
  File "/home/tnowodzinski/.local/lib/python2.7/site-packages/aws_adfs/login.py", line 154, in _authenticate
    html = ET.fromstring(response.text.decode('utf8'), ET.HTMLParser())
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u017a' in position 705: ordinal not in range(128)
```

**Comment by brandond** [comment]
I am pretty sure this explicit decoding is unnecessary now that we're using ET instead of beautifulsoup. I suspect that one of the Python 3 fixes in https://github.com/venth/aws-adfs/pull/7 will fix this for Python 2 as well.

**Comment by venth** [comment]
I think, that the issue is related to missing encoding in headers and passed Accept-Language.
> headers={'Accept-Language': os.environ['LANG'][:2]},
It should be constant and set probably to en_US. In content-type header there should be charset utf-8 mentioned.

**Comment by venth** [comment]
Reproduced. I was able to reproduce the issue by setting 

> headers={'Accept-Language': 'pl'}

Changing it to: 

> headers={'Accept-Language': 'en'}

solved the issue.

**Comment by brandond** [comment]
Yeah, since we're pulling the failure messages directly out of the HTML document, I was trying to allow for some localization by reading the language from the user's environment. This means that if the user has their terminal language set to non-English, parsing may fail due to the fact that the input stream is already UTF-8 with non-ASCII characters.

**Comment by venth** [comment]
Exactly. Since there is no need to translate the interesting output. I think that we could stick with english.

**Comment by venth** [comment]
@dzinek, there is new version released. Please verify, if the issue still exists.

**Comment by dzinek** [comment]
Works, thanks.
