### ISSUE TITLE
aws-adfs installs with botocore-1.8.15, but requires botocore-1.8.17? both?

### ISSUE THREAD

**Issue by worc** [venth/aws-adfs#65]
I have a fresh install of Python 3.6.4 on Windows 10 and ran `pip install aws-adfs` and then tried running `aws-adfs` from the command line and ran into an error:

```
C:\WINDOWS\system32>aws-adfs
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.8.15 (c:\python36\lib\site-packages), Requirement.parse('botocore<1.9.0,>=1.8.17'), {'boto3'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\Scripts\aws-adfs-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.8.15 (c:\python36\lib\site-packages), Requirement.parse('botocore<1.9.0,>=1.8.17'), {'boto3'})
```

Looking back at the installation of `aws-adfs` I see that it downloads `botocore-1.8.15`:

```
C:\WINDOWS\system32>pip install aws-adfs
Collecting aws-adfs
  Using cached aws-adfs-0.4.5.tar.gz
Collecting lxml (from aws-adfs)
  Downloading lxml-4.1.1-cp36-cp36m-win_amd64.whl (3.5MB)
    100% |████████████████████████████████| 3.6MB 355kB/s
Collecting click (from aws-adfs)
  Using cached click-6.7-py2.py3-none-any.whl
Collecting botocore==1.8.15 (from aws-adfs)
  Using cached botocore-1.8.15-py2.py3-none-any.whl

 ...
```

So, thinking I'm looking at a version number mismatch, I ran `pip install --upgrade botocore` and `botocore-1.8.17` was installed while `1.8.15` was uninstalled. However, running `aws-adfs` this time also leads to a version conflict:

```
C:\WINDOWS\system32>aws-adfs
Traceback (most recent call last):
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 659, in _build_master
    ws.require(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 967, in require
    needed = self.resolve(parse_requirements(requirements))
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 858, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.8.17 (c:\python36\lib\site-packages), Requirement.parse('botocore==1.8.15'), {'aws-adfs', 'awscli'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Python36\Scripts\aws-adfs-script.py", line 6, in <module>
    from pkg_resources import load_entry_point
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3017, in <module>
    @_call_aside
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 3030, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 661, in _build_master
    return cls._build_from_requirements(__requires__)
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 674, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "c:\python36\lib\site-packages\pkg_resources\__init__.py", line 853, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'botocore==1.8.15' distribution was not found and is required by aws-adfs, awscli
```

So, `aws-adfs` is still looking for `botocore-1.8.15`? And also `awscli` is expecting that version too?

I could keep trying to upgrade or downgrade or switch dependencies around, but at this point I think I might be doing something wrong or I've run into an installation bug. What should be my next step?

**Comment by subiera** [comment]
Similar if not same issue on my end:

`Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>
    @_call_aside
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3081, in _call_aside
    f(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3108, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 660, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 673, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 851, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (botocore 1.8.15 (/Library/Python/2.7/site-packages), Requirement.parse('botocore<1.9.0,>=1.8.20'), set(['boto3']))`

pip freeze of my environment:

`altgraph==0.10.2
asn1crypto==0.24.0
astroid==1.6.0
aws-adfs==0.4.5
awscli==1.14.11
backports.functools-lru-cache==1.4
bdist-mpkg==0.5.0
beautifulsoup4==4.6.0
bonjour-py==0.3
boto==2.48.0
boto3==1.5.6
botocore==1.8.15
certifi==2017.11.5
cffi==1.11.2
chardet==3.0.4
click==6.7
colorama==0.3.7
configparser==3.5.0
cryptography==2.1.4
docutils==0.14
enum34==1.1.6
futures==3.2.0
idna==2.6
ipaddress==1.0.19
isort==4.2.15
jmespath==0.9.3
lazy-object-proxy==1.3.1
lxml==4.1.1
macholib==1.5.1
matplotlib==1.3.1
mccabe==0.6.1
modulegraph==0.10.4
ntlm-auth==1.0.6
numpy==1.8.0rc1
py2app==0.7.3
pyasn1==0.4.2
pycparser==2.18
pylint==1.8.1
pyobjc-core==2.5.1
pyobjc-framework-Accounts==2.5.1
pyobjc-framework-AddressBook==2.5.1
pyobjc-framework-AppleScriptKit==2.5.1
pyobjc-framework-AppleScriptObjC==2.5.1
pyobjc-framework-Automator==2.5.1
pyobjc-framework-CFNetwork==2.5.1
pyobjc-framework-Cocoa==2.5.1
pyobjc-framework-Collaboration==2.5.1
pyobjc-framework-CoreData==2.5.1
pyobjc-framework-CoreLocation==2.5.1
pyobjc-framework-CoreText==2.5.1
pyobjc-framework-DictionaryServices==2.5.1
pyobjc-framework-EventKit==2.5.1
pyobjc-framework-ExceptionHandling==2.5.1
pyobjc-framework-FSEvents==2.5.1
pyobjc-framework-InputMethodKit==2.5.1
pyobjc-framework-InstallerPlugins==2.5.1
pyobjc-framework-InstantMessage==2.5.1
pyobjc-framework-LatentSemanticMapping==2.5.1
pyobjc-framework-LaunchServices==2.5.1
pyobjc-framework-Message==2.5.1
pyobjc-framework-OpenDirectory==2.5.1
pyobjc-framework-PreferencePanes==2.5.1
pyobjc-framework-PubSub==2.5.1
pyobjc-framework-QTKit==2.5.1
pyobjc-framework-Quartz==2.5.1
pyobjc-framework-ScreenSaver==2.5.1
pyobjc-framework-ScriptingBridge==2.5.1
pyobjc-framework-SearchKit==2.5.1
pyobjc-framework-ServiceManagement==2.5.1
pyobjc-framework-Social==2.5.1
pyobjc-framework-SyncServices==2.5.1
pyobjc-framework-SystemConfiguration==2.5.1
pyobjc-framework-WebKit==2.5.1
pyOpenSSL==17.5.0
pyparsing==2.0.1
python-dateutil==2.6.1
pytz==2013.7
PyYAML==3.12
requests==2.18.4
requests-ntlm==1.1.0
rsa==3.4.2
s3transfer==0.1.12
scipy==0.13.0b1
singledispatch==3.4.0.3
six==1.11.0
urllib3==1.22
vboxapi==1.0
wrapt==1.10.11
xattr==0.6.4
zope.interface==4.1.1`

**Comment by venth** [comment]
Corrected in version of aws-adfs: 0.4.7

**Comment by worc** [comment]
i've got aws-adfs 0.4.7 working now on both python 3.6.4 and 2.7.14 (work and home machines running windows 10). thanks!

**Comment by venth** [comment]
👍
