### ISSUE TITLE
Errors while attempting to log in from windows 10

### ISSUE THREAD

**Issue by ndrwtrsk** [venth/aws-adfs#69]
I attempted to log in to aws through adfs on windows 10 using this glorious tool but got following error:

Error with verbose:
```
~ $ aws-adfs -v login --adfs-host=some.adfs.host.com --no-ssl-verification
2018-01-10 10:33:22,544 [html_roles_fetcher html_roles_fetcher.py:fetch_html_encoded_roles] [14344-MainProcess] [4696-MainThread] - DEBUG: Attempt to load authentication cookies into session failed. Re-authentication will be performed. The error: [Errno 2] No such file or directory: 'C:\\Users\\ato05/.aws\\adfs_cookies'
2018-01-10 10:33:22,546 [connectionpool connectionpool.py:_new_conn] [14344-MainProcess] [4696-MainThread] - DEBUG: Starting new HTTPS connection (1): some.adfs.host.com
c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2018-01-10 10:33:22,779 [connectionpool connectionpool.py:_make_request] [14344-MainProcess] [4696-MainThread] - DEBUG: https://some.adfs.host.com:443 "POST /adfs/ls/IdpInitiatedSignOn.aspx?loginToRp=urn:amazon:webservices HTTP/1.1" 302 0
c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\urllib3\connectionpool.py:858: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
  InsecureRequestWarning)
2018-01-10 10:33:22,821 [connectionpool connectionpool.py:_make_request] [14344-MainProcess] [4696-MainThread] - DEBUG: https://some.adfs.host.com:443 "GET /adfs/ls/wia?loginToRp=urn:amazon:webservices HTTP/1.1" 401 0
Traceback (most recent call last):
  File "C:\Users\ato05\scoop\apps\python\current\scripts\aws-adfs-script.py", line 11, in <module>
    load_entry_point('aws-adfs==0.4.8', 'console_scripts', 'aws-adfs')()
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\aws_adfs\login.py", line 82, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\aws_adfs\authenticator.py", line 19, in authenticate
    password=password,
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\aws_adfs\html_roles_fetcher.py", line 76, in fetch_html_encoded_roles
    data=data
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 190, in _response_hook
    return self._retry_using_http_Negotiate_auth(r, scheme, kwargs)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\requests_negotiate_sspi\requests_negotiate_sspi.py", line 73, in _retry_using_http_Negotiate_auth
    clientauth = sspi.ClientAuth(scheme, targetspn=targetspn, auth_info=self._auth_info)
  File "c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages\win32\lib\sspi.py", line 111, in __init__
    None, auth_info)
ValueError: year 30828 is out of range
```

some info:
 ```
~ $ [Environment]::OSVersion
Platform ServicePack Version      VersionString
-------- ----------- -------      -------------
 Win32NT             10.0.15063.0 Microsoft Windows NT 10.0.15063.0

$ pip --version
pip 9.0.1 from c:\users\ato05\scoop\apps\python\3.6.3\lib\site-packages (python 3.6)

$ python --version
Python 3.6.3

$ aws-adfs --version
0.4.8

$ aws --version
aws-cli/1.14.11 Python/2.7.9 Windows/8 botocore/1.8.15
```

**Comment by rucoetzer** [comment]
Any luck with this? I have exactly the same issue on my Win 10 machine.

**Comment by venth** [comment]
It looks like the issue is related to native python library sspi and its windows implementation. I try different approaches to find workaround for the issue. In meanwhile I can provide in docker and docker-compose yaml files to authenticate with aws-adfs on Windows manchine with docker container and then use awscli directly in windows. Please let me know, if you’re interested.

**Comment by connesc** [comment]
Same problem here on Windows 7.
Would the Docker approach be able to use SSPI anyway? Prompting for user credentials is not an option in my case.

**Comment by ndrwtrsk** [comment]
Hello, with venth's great help I got it working. I'll post Dockerfile and docker-compose.yml that I use aswell as a powershell script to automate/shorten process a bit.

Dockerfile
```
FROM debian:stretch
 
RUN apt-get update && \
   apt-get install -y curl python && \
   curl -L https://bootstrap.pypa.io/get-pip.py | python && \
   pip install aws-adfs
 
VOLUME /root/.aws
```

docker-compose.yml - change {your_user} for you actual directory
```
version: '3'
 
services:
  aws-adfs:
    build:
      context: .
    volumes:
      - C:\Users\{your_user}\.aws:/root/.aws
```

aws-adfs-login.ps1
```
docker-compose run --rm aws-adfs aws-adfs login --adfs-host=your-adfs-host.com --no-ssl-verification
```

Now simply put Dockerfile and docker-compose.yml in one dir and fire off the script above while in this directory.

Voilà! It is done.

**Comment by venth** [comment]
Would you like to help me to diagnose the issue? There is a new version of: pypiwin32 library. The stack trace indicates that this library causes the issue. I hope that newest version of the library will solve the issue.
First, please provide results of:
`pip freeze` command
then please upgrade pypiwin32 library by using the command: `pip install --upgrade pypiwin32` and
try to use `aws-adfs login ...`

**Comment by ndrwtrsk** [comment]
I will try it first thing Monday morning when I have access to windows machine.

**Comment by connesc** [comment]
I had already deleted my Python 3 install, so no `pip freeze` for me.
However, I confirm that `aws-adfs login` is now working on a fresh Python 3 install! :tada:

**Comment by greensmith** [comment]
Hi I'm getting the same error running on a Windows 7 machine, 

Python 3.6.3, pip 9.0.1, aws-adfs 0.6.1 & aws-cli 1.14.40.

pip is telling me that pypiwin32 is up-to-date.

I'm using the container work around  for now.

**Comment by venth** [comment]
@greensmith, please, paste the results of `pip freeze` command.

**Comment by greensmith** [comment]
asn1crypto==0.24.0            
aws-adfs==0.6.1               
awscli==1.14.22               
boto3==1.5.12                 
botocore==1.8.26              
certifi==2018.1.18            
cffi==1.11.4                  
chardet==3.0.4                
click==6.7                    
colorama==0.3.7               
configparser==3.5.0           
cryptography==2.1.4           
docutils==0.14                
idna==2.6                     
isapi-wsgi==0.4.2             
jmespath==0.9.3               
lxml==4.1.1                   
pyasn1==0.4.2                 
pycparser==2.18               
pyOpenSSL==17.5.0             
pypiwin32==220                
python-dateutil==2.6.1        
PyYAML==3.12                  
requests==2.18.4              
requests-negotiate-sspi==0.3.4
rsa==3.4.2                    
s3transfer==0.1.13            
six==1.11.0                   
urllib3==1.22

**Comment by venth** [comment]
@greensmith, please, try to downgrade pypiwin32 by execution command: `pip install "pypiwin32==219"`

**Comment by greensmith** [comment]
219 doesn't seem to be compatible with Python 3.6.

Pip will only install 220.

I can download the 222 whl from https://pypi.python.org/pypi/pywin32 and install that - but I still get the same year out of range error.

**Comment by venth** [comment]
The direct cause of the issue is pypiwin32 library or changes in Windows SDK wrapped by this library. This library is used by requests-negotiate-sspi. I wonder which version of pypiwin32 works correctly. Unfortunately I don't have access to windows machine to perform necessary research. My hope was that the version 219 will work.

**Comment by greensmith** [comment]
No worries, the docker workaround is suitable for my needs at the moment. 
Maybe if I get more time I can look into this in more detail.

**Comment by pdecat** [comment]
This is supposed to be fixed since pywin32 b222, see:

https://bugs.python.org/issue29921#msg402486

https://github.com/mhammond/pywin32/issues/748#issuecomment-359223029

https://github.com/mhammond/pywin32/commit/07202650d21e8fa7f3053ff1d4665363315cefce

https://github.com/mhammond/pywin32/blob/b222/CHANGES.txt#L24-L26
