### ISSUE TITLE
NO_PROXY Environment Variable

### ISSUE THREAD

**Issue by jacobleonwoffenden** [venth/aws-adfs#77]
Hi,

I'm trying to use `aws-adfs` on macOS 10.13.2, however I keep getting the following error:
```
$ aws-adfs login --adfs-host=<redacted adfs server>
Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/aws_adfs/login.py", line 102, in login
    principal_roles, assertion, aws_session_duration = authenticator.authenticate(config)
  File "/Library/Python/2.7/site-packages/aws_adfs/authenticator.py", line 19, in authenticate
    password=password,
  File "/Library/Python/2.7/site-packages/aws_adfs/html_roles_fetcher.py", line 76, in fetch_html_encoded_roles
    data=data
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/Library/Python/2.7/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/Library/Python/2.7/site-packages/requests/adapters.py", line 490, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine("''",))
```

In my previous attempts at using the `samlapi.py` script that [AWS provide](https://aws.amazon.com/blogs/security/how-to-implement-federated-api-and-cli-access-using-saml-2-0-and-ad-fs/), I got around the proxy by using `session.trust_env = False`

To get cURL working with the ADFS server, I need to export `NO_PROXY="<redacted adfs server>"`

Any ideas on how I can get `aws-afds` to work in this scenario?

**Comment by venth** [comment]
Currently session property: trust_env isn't setup. Till the support is added please consider to use docker workaround described here: https://github.com/venth/aws-adfs/issues/69
