### ISSUE TITLE
After login, when selecting a role throws the below error

### ISSUE THREAD

**Issue by narendergakka** [venth/aws-adfs#85]
Using the command to login to the "aws-adfs login --adfs-host=domain.domain.com  --no-ssl-verification" however after it successfully authenticates against the domain and displays the roles available, the Role selection throws the below error,

Does anyone know why this behaviour?

Selection: 0
Traceback (most recent call last):
  File "/usr/local/bin/aws-adfs", line 9, in <module>
    load_entry_point('aws-adfs==0.8.0', 'console_scripts', 'aws-adfs')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/aws_adfs/login.py", line 159, in login
    DurationSeconds=3600,
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/local/lib/python2.7/dist-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the AssumeRoleWithSAML operation: Principal ARN is invalid

**Comment by pkccd** [comment]
I am having the same issue with one of my accounts on version 12 of the aws-adfs script.  I recreated the roles and even created additional roles in that particular account and it continues.  Works fine via ADFS Idpinitiated signon page.


Traceback (most recent call last):
  File "/usr/bin/aws-adfs", line 9, in <module>
    load_entry_point('aws-adfs==0.12.0', 'console_scripts', 'aws-adfs')()
  File "/usr/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/aws_adfs/login.py", line 185, in login
    DurationSeconds=int(config.session_duration),
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 314, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/usr/lib/python2.7/site-packages/botocore/client.py", line 612, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ValidationError) when calling the AssumeRoleWithSAML operation: Principal ARN is invalid

**Comment by pkccd** [comment]
@narendergakka Check the claim rules on the sso provider and ensure there are no typographical errors.  We have a RegExReplace in our claim rule and there as a space in front of the ARN that was causing the same error.
