### ISSUE TITLE
pywin32-223

### ISSUE THREAD

**Issue by imtpalmer** [venth/aws-adfs#94]
On Windows 10, Python 3.

Traceback (most recent call last):
  File "C:\Anaconda3\x64\Scripts\aws-adfs-script.py", line 11, in <module>
    load_entry_point('aws-adfs==0.10.1', 'console_scripts', 'aws-adfs')()
  File "C:\Anaconda3\x64\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\Anaconda3\x64\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\Anaconda3\x64\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Anaconda3\x64\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Anaconda3\x64\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\Anaconda3\x64\lib\site-packages\aws_adfs-0.10.1-py3.6.egg\aws_adfs\login.py", line 120, in login
  File "C:\Anaconda3\x64\lib\site-packages\aws_adfs-0.10.1-py3.6.egg\aws_adfs\authenticator.py", line 19, in authenticate
  File "C:\Anaconda3\x64\lib\site-packages\aws_adfs-0.10.1-py3.6.egg\aws_adfs\html_roles_fetcher.py", line 76, in fetch_html_encoded_roles
  File "C:\Anaconda3\x64\lib\site-packages\requests\sessions.py", line 555, in post
    return self.request('POST', url, data=data, json=json, **kwargs)
  File "C:\Anaconda3\x64\lib\site-packages\requests\sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Anaconda3\x64\lib\site-packages\requests\sessions.py", line 640, in send
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Anaconda3\x64\lib\site-packages\requests\sessions.py", line 640, in <listcomp>
    history = [resp for resp in gen] if allow_redirects else []
  File "C:\Anaconda3\x64\lib\site-packages\requests\sessions.py", line 218, in resolve_redirects
    **adapter_kwargs
  File "C:\Anaconda3\x64\lib\site-packages\requests\sessions.py", line 625, in send
    r = dispatch_hook('response', hooks, r, **kwargs)
  File "C:\Anaconda3\x64\lib\site-packages\requests\hooks.py", line 31, in dispatch_hook
    _hook_data = hook(hook_data, **kwargs)
  File "C:\Anaconda3\x64\lib\site-packages\requests_negotiate_sspi-0.3.4-py3.6.egg\requests_negotiate_sspi\requests_negotiate_sspi.py", lin190, in _response_hook
  File "C:\Anaconda3\x64\lib\site-packages\requests_negotiate_sspi-0.3.4-py3.6.egg\requests_negotiate_sspi\requests_negotiate_sspi.py", lin73, in _retry_using_http_Negotiate_auth
  File "C:\Anaconda3\x64\lib\site-packages\win32\lib\sspi.py", line 111, in __init__
    None, auth_info)
ValueError: year 30828 is out of range

The above error is from a bug in pywin32 which has been deprecated.. Is this a dependency for aws-adfs?

**Comment by venth** [comment]
It's a transitive dependency of `aws-adfs`. `py-win32` comes with `requests-negotiate-sspi` which is the direct dependency.

**Comment by venth** [comment]
It's [reported](https://sourceforge.net/p/pywin32/bugs/748/). Unfortunately it's still open.

**Comment by pdecat** [comment]
This is supposed to be fixed since pywin32 b222, see:

https://bugs.python.org/issue29921#msg402486

https://github.com/mhammond/pywin32/issues/748#issuecomment-359223029

https://github.com/mhammond/pywin32/commit/07202650d21e8fa7f3053ff1d4665363315cefce

https://github.com/mhammond/pywin32/blob/b222/CHANGES.txt#L24-L26

**Comment by pdecat** [comment]
Duplicate of #69
